### ISSUE TITLE
Column filtering

### ISSUE THREAD

**Issue by jack-watts** [SteveLLamb/mediastandards-registry#2]
Added a first pass attempt at creating filters like excel per column;
[https://github.com/SteveLLamb/doc-registry/blob/7aca979e8b5dc71f7a8cd2bf3f132d0168abbc13/src/site/documents.js#L20]

An alternate option here:
[https://github.com/SteveLLamb/doc-registry/blob/7aca979e8b5dc71f7a8cd2bf3f132d0168abbc13/src/site/documents.js#L43]

dependency: [(https://github.com/koalyptus/TableFilter)]

**Comment by SteveLLamb** [comment]
Closed with current functionality
