### ISSUE TITLE
Status Logic update

### ISSUE THREAD

**Issue by SteveLLamb** [SteveLLamb/mediastandards-registry#6]
Remove status as enum value list, and base current status on page on logic rules:

- If `Draft:true`, no other status shall be present
- If `Unknown:true`, no other status shall be present

- If `Active:true`, then (`Superseded:true` and/or `Withdrawn:true`) shall not be present

- Once `Amended:true`, shall not ever be `Amended:false`
-- May be `Amended:true` and `Active:true`

- Once `Reaffirmed:true`, shall not ever be `Reaffirmed:false`
-- May be `Reaffirmed:true` and `Active:true`

- Once `Stabilized:true`, shall not ever be `Stabilized:false`
-- May be `Stabilized:true` and `Active:true`

- Once `Superseded:true`, shall not ever be `Superseded:false`
-- If `Superseded:true`, then `Active:false`

- Once `Withdrawn:true`, shall not ever be `Withdrawn:false`
-- If `Withdrawn:true`, then `Active:false`

**Comment by SteveLLamb** [comment]
Also need to figure out how to map the above to "current" status for preview view.

**Comment by jack-watts** [comment]
Since each Status value is of type bool, this could be achieved through a Switch statement.

Example

**HBS Template**
```
<div>
{{#switch '1'}} 
  {{#case '1'}} This is case one {{/case}} 
  {{#case '2'}} This is case two {{/case}}
{{/switch}}
</div>
```

**Register Helper**
```
Handlebars.registerHelper('switch', function(value, options) {
  this.switch_value = value;
  return options.fn(this);
});

Handlebars.registerHelper('case', function(value, options) {
  if (value == this.switch_value) {
    return options.fn(this);
  }
});
```

**HTML Output**
```
<div>
    This is case one
</div>
```


Reference: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)

**Comment by SteveLLamb** [comment]
I'm not concerned with the rendering on the page for each document, it's the document statuses that are preloaded in the references and related documents sections, which is built here:

`/* load the doc Statuses, Labels */
  
  const docStatuses = {}
  const docLabels = {}

  registry.forEach(item => { docStatuses[item.docId] = item.status} );
  registry.forEach(item => { docLabels[item.docId] = (item.label)} );

  hb.registerHelper("getStatus", function(docId) {
    return docStatuses[docId];
  });

  hb.registerHelper("getLabel", function(docId) {
    return docLabels[docId];
  });
,
