### ISSUE TITLE
`DCinema` appears twice in the filter list

### ISSUE THREAD

**Issue by radford-for-smpte** [SteveLLamb/mediastandards-registry#7]
Not sure why, but this happens:

<img width="339" alt="Screen Shot 2020-11-10 at 7 34 20 PM" src="https://user-images.githubusercontent.com/11240184/98762361-4f6eff00-238c-11eb-8248-e3cc3f410dd6.png">

**Comment by SteveLLamb** [comment]
Yep, it's in the filtering script 2x. Good catch, will update shortly.
